### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by thewchan**
The readme currently said public domain or equivalent, MIT is pretty much "do whatever you want".

### CODE REVIEW

**Comment by thewchan** [comment]
@Tronic here as well?

**Comment by Tronic** [comment]
@thewchan We'll try to push out new releases of each package soon. That is handled by @ahopkins and there could be other ongoing development that needs to be wrapped prior to making a release.

**Comment by thewchan** [comment]
Sound good. Thanks again!

**Comment by ahopkins** [comment]
Will get to that shortly 😎.

**Pull request merged**
